name: 'my second workflow'

on: 'workflow_dispatch'

jobs:
  "firstjob":
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
      - name: 'file creation'
        run: echo "hii hello" > data.txt
      - name: 'reading file'
        run: cat data.txt
