name: "react native bare project"
on: "workflow_dispatch"
jobs:
  "project_setup":
    runs-on: ubuntu-latest
    steps:
      - name: "code checkout"
        uses: actions/checkout@v4
      - name: "node setup"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: SampleProj/package-lock.json
      - name: "installing dependencies"
        working-directory: SampleProj
        run: npm ci
      - name: "running lint"
        working-directory: SampleProj
        run: npm run lint
      - name: "checking typescript errors"
        working-directory: SampleProj
        run: npx tsc --noEmit
  android_build:
    runs-on: ubuntu-latest
    needs: project_setup
    steps:
      - name: "code checkout"
        uses: actions/checkout@v4
      - name: "node setup"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: SampleProj/package-lock.json
      - name: "java setup"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "installing dependencies"
        working-directory: SampleProj
        run: npm ci
      - name: "building android debug apk"
        working-directory: SampleProj/android
        run: ./gradlew assembleDebug
      - name: "uploading apk"
        uses: actions/upload-artifact@v4
        with:
          name: "sample-debug-apk"
          path: SampleProj/android/app/build/outputs/apk/debug/app-debug.apk
  download_apk:
    runs-on: ubuntu-latest
    needs: android_build
    steps:
      - name: "downloading apk artifact"
        uses: actions/download-artifact@v4
        with:
          name: "sample-debug-apk"
          path: "./downloads"

      - name: "checking downloaded apk"
        run: |
          echo "Downloaded files:"
          ls -ltr ./downloads
          echo "APK details:"
          ls -lh ./downloads/app-debug.apk
