name: pipe bash

on: 'workflow_dispatch'

jobs:
  'multi_commands':
   runs-on: ubuntu-latest
   steps:
     - name: 'checkout into code'
       uses: actions/checkout@v4
     - name: 'multi commands with pipe'
       run: |
           ls -ltr
           echo 'hello world'
           date
           pwd
           cat index.js
           echo 'job completed'
